
CREATE TABLE users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  email TEXT UNIQUE,
  password_hash TEXT,
  role TEXT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE requests (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER,
  description TEXT,
  status TEXT DEFAULT 'OPEN'
);

CREATE TABLE offers (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  request_id INTEGER,
  helper_id INTEGER,
  message TEXT,
  status TEXT DEFAULT 'PENDING'
);

CREATE TABLE messages (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  sender_id INTEGER,
  receiver_id INTEGER,
  body TEXT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
